version: '3'
services:

  sportsbet-mysql:
    image: "mysql:8"
    container_name: sportsbet-mysql
    volumes:
      - sportsbet-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=sport_user
      - MYSQL_DATABASE=sportsbet
 
  db_seeder:
    image: mysql:8
    volumes:
      - ./database/sportsbet-dump.sql:/db.sql
    entrypoint: [ "bash", "-c", "sleep 10 && mysql --user=root -h sportsbet-mysql -pS3cret --protocol=tcp --port=3306 sportsbet < /db.sql && exit"] 
    depends_on:
      - sportsbet-mysql

  sportsbet-backend:
    image: "rvabrilot/sportsbet@sha256:a9fac3455d7a475554048d987e00ea68afd013ed5eaf0586cc3604a5c5ec7b48"
    container_name: sportsbet-backend
    environment:
      - DB_SERVER=sportsbet-mysql
      - MYSQL_DATABASE=sportsbet
      - MYSQL_USER=sport_user
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_HOST=sportsbet-mysql
    ports:
      - 8080:8080
    links:
      - sportsbet-mysql
    depends_on:
      - db_seeder

  sportsbet-frontend:
    image: "rvabrilot/sportsbet@sha256:7a2309be8509150f4a4796a9f22187b6701bbf9fc53bf7e53257f0c7b6491082"
    container_name: sportsbet-frontend
    ports:
      - 80:3000
    links:
      - sportsbet-backend
    depends_on:
      - db_seeder
  
  sportsbet-admin:
    image: "rvabrilot/sportsbet@sha256:dbe2e91f2b9ca43a2fe8b5e3970f58949c3a56b12e64e52983e61f6830ebf9b1"
    container_name: sportsbet-admin
    ports:
      - 20900:3000
    links:
      - sportsbet-backend
    depends_on:
      - db_seeder

volumes:
  sportsbet-data:
